### ISSUE TITLE
indels and dbSNPs VCF should allow gz compressed format (.vcf.gz)

### ISSUE THREAD

**Issue by mfoll** [IARCbioinfo/alignment-nf#9]
I guess one only has to add a `*` after the `vcf`extension in these lines:
```
indelsvcf=`ls !{params.GATK_bundle}/*indels*.vcf
dbsnpvcfs=(`ls !{params.GATK_bundle}/*dbsnp*.vcf
```

**Comment by mfoll** [comment]
@cahaisv needs that

**Comment by cahaisv** [comment]
If you just add a *, you will also select the index file *indels*.vcf.gz.tbi

**Comment by cahaisv** [comment]
you have to filter the tbi files :

indelsvcf=&grave;ls !{params.GATK_bundle}/*indels*.vcf* | grep -v ".tbi"&grave;
dbsnpvcfs=&grave;s !{params.GATK_bundle}/*dbsnp*.vcf*  | grep -v ".tbi"&grave;

**Comment by mfoll** [comment]
Hi @cahaisv, please make this change and create a pull request, so that @nalcala can check it and merge the branch.

**Comment by nalcala** [comment]
Thanks to both of you! Please do not hesitate to make pull requests and contribute if you have other ideas of enhancements
